# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam', '0002_auto_20170407_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
